# Generated by Django 3.2.9 on 2021-11-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
